import ToDoList from "./components/ToDoList";
import { Timer } from "./components/Timer";
import { useState, useEffect } from "react";
import { AddForm } from "./components/AddForm";
import "./App.css";

const fetchUrl =
  "https://gist.githubusercontent.com/benna100/391eee7a119b50bd2c5960ab51622532/raw";

function App() {
  const [todos, setTodos] = useState([]);

  //Fetching todos from API on window load
  useEffect(() => {
    addTodosFromAPI(fetchUrl);
  }, []);

  async function addTodosFromAPI(fetchUrl) {
    const response = await fetch(fetchUrl);
    const fetchedTodos = await response.json();
    setTodos(fetchedTodos);
  }

  //Actions with the list
  //updateDescription is going to be passed to the ToDoItem component
  const updateDescription = (e, description) => {
    const todoToUpdate = e.target.parentNode.id;
    console.log(todoToUpdate);
    const updatedTodo = todos.map((todo) => {
      // String() is used since id's data type from fetch is a number, while ids generated by a randomizer are strings. I unified the data type to avoid bugs on the event handler
      if (String(todo.id) === String(todoToUpdate)) {
        todo.description = description;
      }
      return todo;
    });
    setTodos(updatedTodo);
  };

  function deleteTodo(e) {
    console.log(e.target.parentNode.id);
    const todoToDelete = e.target.parentNode.id;
    const newToDos = todos.filter(
      (todo) => String(todo.id) !== String(todoToDelete)
    );
    // String() is used since id's data type from fetch is a number, while ids generated by a randomizer are strings. I unified the data type to avoid bugs on the event handler
    console.log(newToDos);
    setTodos(newToDos);
  }

  return (
    <div className="App">
      <h1>Todo-List by Alina</h1>
      <Timer />
      <AddForm todos={todos} setTodos={setTodos} />
      <ToDoList
        toDoList={todos}
        onDelete={deleteTodo}
        updateDescription={updateDescription}
      />
    </div>
  );
}

export default App;
